// <auto-generated />
using System;
using LocationMaster_API.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LocationMaster_API.Migrations
{
    [DbContext(typeof(LocationMasterContext))]
    [Migration("20200106140931_ceva_jmenar")]
    partial class ceva_jmenar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Attraction", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid");

                    b.HasKey("AttractionId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid");

                    b.HasKey("PhotoId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            PhotoId = new Guid("6b54beff-df42-48b0-a1cd-bb1e82a078b7"),
                            Path = "/StaticFiles/Images/ProfileImages/DefaultProfileImage.png"
                        },
                        new
                        {
                            PhotoId = new Guid("8a74d481-9e1c-4e4f-9c3c-f49506b69a38"),
                            Path = "/StaticFiles/Images/ProfileImages/DefaultProfileImage.png"
                        },
                        new
                        {
                            PhotoId = new Guid("1d4c6957-9fa0-46dc-9a04-a714eafba70e"),
                            Path = "/StaticFiles/Images/ProfileImages/DefaultProfileImage.png"
                        });
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Place", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .HasColumnType("text");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<float>("TicketPrice")
                        .HasColumnType("real");

                    b.HasKey("PlaceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ReviewId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("AllowedRoles")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfileImagePhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("ProfileImagePhotoId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1988ca44-9533-488d-b50a-e75d26da78a5"),
                            AllowedRoles = new[] { "admin" },
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FirstName = "Comanel",
                            LastName = "Gigica",
                            Password = "$MYHASH$V1$10000$hwapC7G1RBS9iHOHq/P58jUV3mg8ncqKFaNj0o1gqm+JX8gzs0ce3LEgpmFMjLNdFpgUWJEsikP8gIisSHyDfIl6vYMl5KVVvRML2jEfSG8=",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = new Guid("ceab63b6-95db-4765-8fbb-e3b8640b10f1"),
                            AllowedRoles = new[] { "moderator" },
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "moderator@gmail.com",
                            FirstName = "Comanel",
                            LastName = "Jhony",
                            Password = "$MYHASH$V1$10000$+efBlE4CCzGlYTQyr0wkTBCuHDvAeU1DMCBdrP61ubZ4lwvAuyKbro8HzOxPtuPrtCMePDYkZoeLXhezYjiwm3qtxy/qgxNwsPZOwFdwxeo=",
                            Username = "moderator"
                        },
                        new
                        {
                            UserId = new Guid("a2d5e9bd-4dd7-40f9-83d3-5cfcfb19645c"),
                            AllowedRoles = new[] { "user" },
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@gmail.com",
                            FirstName = "Comanel",
                            LastName = "Florinel",
                            Password = "$MYHASH$V1$10000$UvjXnB+I3gAj8svnSgb7uIALZvjwt5dvEH7NbLU+X1BWpup6O/eUx1ncHCC3Jnrtq+dQuNFovZKAIEL+z3PVxRVzJ1TVzZsVN4xPHooz1HQ=",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Attraction", b =>
                {
                    b.HasOne("LocationMaster_API.Domain.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");

                    b.HasOne("LocationMaster_API.Domain.Entities.Place", null)
                        .WithMany("Attractions")
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Photo", b =>
                {
                    b.HasOne("LocationMaster_API.Domain.Entities.Place", null)
                        .WithMany("Photos")
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Place", b =>
                {
                    b.HasOne("LocationMaster_API.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("LocationMaster_API.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Review", b =>
                {
                    b.HasOne("LocationMaster_API.Domain.Entities.Place", null)
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId");

                    b.HasOne("LocationMaster_API.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.User", b =>
                {
                    b.HasOne("LocationMaster_API.Domain.Entities.Photo", "ProfileImage")
                        .WithMany()
                        .HasForeignKey("ProfileImagePhotoId");
                });
#pragma warning restore 612, 618
        }
    }
}
