// <auto-generated />
using System;
using LocationMaster_API.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LocationMaster_API.Migrations
{
    [DbContext(typeof(LocationMasterContext))]
    [Migration("20200112150501_final")]
    partial class final
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Attraction", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid");

                    b.HasKey("AttractionId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid");

                    b.HasKey("PhotoId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            PhotoId = new Guid("d9b66c89-932c-4e6f-a363-0bf919a6121e"),
                            Path = "/StaticFiles/Images/ProfileImages/DefaultProfileImage.png"
                        },
                        new
                        {
                            PhotoId = new Guid("65a2ea00-f3f8-48f0-a1ea-30a7ff4c8c2a"),
                            Path = "/StaticFiles/Images/ProfileImages/DefaultProfileImage.png"
                        },
                        new
                        {
                            PhotoId = new Guid("ac2bb3d0-848c-4c12-abe5-371168ee7fbb"),
                            Path = "/StaticFiles/Images/ProfileImages/DefaultProfileImage.png"
                        });
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Place", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .HasColumnType("text");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<float>("TicketPrice")
                        .HasColumnType("real");

                    b.HasKey("PlaceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ReviewId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("AllowedRoles")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfileImagePhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("ProfileImagePhotoId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("19a56856-18d8-4070-943a-714294e34686"),
                            AllowedRoles = new[] { "admin" },
                            BirthDate = new DateTime(2020, 1, 12, 17, 4, 58, 872, DateTimeKind.Local).AddTicks(5439),
                            Email = "admin@gmail.com",
                            FirstName = "Comanel",
                            LastName = "Gigica",
                            Password = "$MYHASH$V1$10000$cxGUQagJgT6k4rqJqQ0cZgQn6YX3ytnqQufGbfLl5p1yHa3neRV7k6FBJZhSEqiJEONPz1jr5JprxVd8HgrXDvM8bV3Pem02WkB+mDIyOUU=",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = new Guid("ba237a6d-a260-43e3-afee-8222e6ea94ac"),
                            AllowedRoles = new[] { "moderator" },
                            BirthDate = new DateTime(2020, 1, 12, 17, 4, 58, 872, DateTimeKind.Local).AddTicks(5439),
                            Email = "moderator@gmail.com",
                            FirstName = "Comanel",
                            LastName = "Jhony",
                            Password = "$MYHASH$V1$10000$ydf/zztvARE2dboWnW2E93uh/SoQ8yoB5xo3t7TyH83o4caElR/VD5gAP3osjLIjbGsdqxkkealGMsKW3dcRbqGlETASMRnMIZ/7T6hUIvw=",
                            Username = "moderator"
                        },
                        new
                        {
                            UserId = new Guid("1d94f0fe-2f9d-4bbb-92b3-6e5b615e08e2"),
                            AllowedRoles = new[] { "user" },
                            BirthDate = new DateTime(2020, 1, 12, 17, 4, 58, 872, DateTimeKind.Local).AddTicks(5439),
                            Email = "user@gmail.com",
                            FirstName = "Comanel",
                            LastName = "Florinel",
                            Password = "$MYHASH$V1$10000$rZFp8JlPznvjq1NX+Y8OWYpQAuGfIMPU+7QatRoNVTTe2FmRCj8UuTo5FkvFVGOToQGT67c6kLJdz84n2O1E/qnpuUWgpJ4ChMCS5qZwYQ0=",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Attraction", b =>
                {
                    b.HasOne("LocationMaster_API.Domain.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");

                    b.HasOne("LocationMaster_API.Domain.Entities.Place", null)
                        .WithMany("Attractions")
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Photo", b =>
                {
                    b.HasOne("LocationMaster_API.Domain.Entities.Place", null)
                        .WithMany("Photos")
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Place", b =>
                {
                    b.HasOne("LocationMaster_API.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("LocationMaster_API.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.Review", b =>
                {
                    b.HasOne("LocationMaster_API.Domain.Entities.Place", null)
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId");

                    b.HasOne("LocationMaster_API.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LocationMaster_API.Domain.Entities.User", b =>
                {
                    b.HasOne("LocationMaster_API.Domain.Entities.Photo", "ProfileImage")
                        .WithMany()
                        .HasForeignKey("ProfileImagePhotoId");
                });
#pragma warning restore 612, 618
        }
    }
}
