version: 2.0
jobs:
 build:
   docker:
     - image: mcr.microsoft.com/dotnet/core/sdk:3.0
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore /LocationMaster/LocationMaster_API
     - run:
         name: Build App
         command:
           dotnet build /LocationMaster/LocationMaster_API
     - run:
         name: Run App
         command:
           dotnet run /LocationMaster/LocationMaster_API